### ISSUE TITLE
[TODO] - 0.5.5 Progress Report & RoadMap

### ISSUE THREAD

**Issue by Ghostipedia** [Frontiers-PackForge/CosmicFrontiers#243]
The RoadMap for 0.5.5 which will released on Oct19th.
This is just a place I can consolidate the rest of what I need to look over and do. Does not fully encompass what this update contains, just what I have left to do.

# Bugs

- [x] ARAM Chip Recipes (Fixed in dev)
- [ ] Modded Sands -> Glass Recipes | Needs a Larger Rework, Upgrade to an 0.6.0 Issue
- [x] Packing Tape Recipes
- [x] Verify None of the FTBFilterSystem Quests are broken still
- [x] Remove BYG Golden Apple Craft
- [ ] Remove Veinmining capability from alt-stonetypes for ores | Needs a Larger Rework, Upgrade to an 0.6.0 Issue

# Content
## Questbook Related

- [x] Some Really Basic Store Rewards for Start - LV Rewards
- [x] Trophies for Multiblocks, Major Ingots, Circuits up to LV
- [x] 100% Steam Chapter Quest Coverage with the new Quest Standard 
- [x] Prepare LUV Chapter for Similar Treatment for 0.6.0
- [x] Add TODO's/Notices to the LV - IV Chapters that they'll remain a WIP and put a main notice on the starting page.

## Steam Overhaul Content
- [x] Mechanical Squeezer Recipe using ULV Parts - Remove Power Cost
- [x] Dimensional Lamp Recipe Changes
- [x] Occultism Storage Recipe Upgrades, made harder etc
- [x] Circuit Board Recipe Rework
- [x] Circuit Part Recipe Rework
- [x] Steam Assembler Recipe
- [x] Steel Framed Bronze Casing Recipe
- [x] Integrated Dynamics Recipes, as well as hide writers that don't have aspects

### Occultism Ritual Dev

- [x] Ritual of Rune Bonding
- [x] Ritual of Arcane Grace
- [x] Ritual of Basic Fusion

Finish the Book Entry Lang, and Mention them in the QB.

## Lore Related
- [x] Finish Cleaning up the story entry for Steam, as well as make sure the start chapter is sorted out.
- [x] Consider a disclaimer for LV+ story/lore nodes being outdated or impartial.
- [x] Fix up the Chapter names in the QB
- [x] Continue to refine the story down, put a narrative freeze on later content for RN.
